### ISSUE TITLE
The texture of Duck.gltf is not loaded

### ISSUE THREAD

**Issue by cx20** [shrekshao/minimal-gltf-loader#5]
I tried to display glTF 2.0 Sample Models with Minimal glTF Loader.

[glTF Test](https://github.com/cx20/gltf-test/tree/2.0)
![image](https://user-images.githubusercontent.com/1833979/28498815-c3282f32-6fe1-11e7-946c-5909cd7350a7.png)

However, it seems that the model using texture is not displayed.

[Minimal glTF Loader + Duck.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/dc56cb32c16e6aa6523ad6a3f90d9e5123c45747/examples/minimal-gltf-loader/index.html?model=Duck&scale=1)
![image](https://user-images.githubusercontent.com/1833979/28498817-dc657310-6fe1-11e7-8b59-898f2b5d32c2.png)

I know that this project is WIP, but I think it would be better to display more models.

**Comment by shrekshao** [comment]
@cx20 Thanks for the feedback!

The thing is that the loader did load the image (open the network tab in the web developer console of your browser to see the transferred image). It's the renderer example that didn't draw the texture. 

Actually, I recently picked up this repo and migrated it to glTF 2. When I first write this for glTF 1, shader program is in the repo, so there's a time that the renderer can render the image, as you can see in the screenshot: 
![](https://github.com/shrekshao/minimal-gltf-loader/blob/master/img/viewer-screenshot-2.png?raw=true)

Since I have no plans for backward compatibility for now, I haven't added texture rendering feature to the renderer example ( Also noted that I focused on the webgl-2 renderer and deleted the webgl-1 example)

Please be sure to pull the newest updates. Also noted I'm afraid this loader is now heavily feature incomplete and in its fast iteration. Sorry about all the inconvenience. You're welcome to add drawing texture to the renderer example. (I'm currently focused on some other features, but I will try to add texture drawing including PBR rendering to the example ASAP)

Thank you again.

**Comment by shrekshao** [comment]
@cx20 Oh my God, didn't notice it was added to your glTF test.... Great pressure.... I will try to fix that ASAP. Thanks!

**Comment by shrekshao** [comment]
@cx20  add basic `baseColorTexture` support, add auto center and scale (fixing gearbox) at the latest `master`

![](https://github.com/shrekshao/minimal-gltf-loader/blob/master/img/viewer-screenshot-duck.png?raw=true)

![](https://github.com/shrekshao/minimal-gltf-loader/blob/master/img/viewer-screenshot-gear-bbox.png?raw=true)

**Comment by cx20** [comment]
@shrekshao Thank you for supporting texture. It was correctly displayed locally.
However, on rawgit.com I will get a [cross origin error](https://cdn.rawgit.com/cx20/gltf-test/53211122894d58aac983f35552c56f04c794437a/examples/minimal-gltf-loader/index.html?model=Duck&scale=1).
```javascript
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The cross-origin image at https://raw.githubusercontent.com/cx20/gltf-test/53211122894d58aac983f35552c56f04c794437a/sampleModels/Duck/glTF/DuckCM.png may not be loaded.
```

This problem can be solved by setting the crossOrigin attribute. please correspond to the cross origin to the processing to load the texture image with glTF Loader.
https://github.com/shrekshao/minimal-gltf-loader/blob/8e76d2a469a45db564b47a53a95103fc8323a172/src/minimal-gltf-loader.js#L920
```javascript
function _loadImage(url, iid, onload) {
    var img = new Image();
    img.crossOrigin = "Anonymous"; // please add
    img.src = url;
    img.onload = function() {
        onload(img, iid);
    };
}
```

**Comment by shrekshao** [comment]
@cx20 Thank you so much! Updated at the latest master.

**Comment by cx20** [comment]
I confirmed that the texture is correctly displayed even on rawgit.com.

[glTF Test](https://github.com/cx20/gltf-test/tree/2.0)
![image](https://user-images.githubusercontent.com/1833979/28778462-4bd096e0-763a-11e7-9fa0-54a805a00490.png)

[Minimal glTF Loader + Duck.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/ee4e09519b8a13e7abc0e03bdcf0223a534f7e31/examples/minimal-gltf-loader/index.html?model=Duck&scale=1)
![image](https://user-images.githubusercontent.com/1833979/28778517-897a867c-763a-11e7-87f3-ffc394a06103.png)

Since Duck.gltf is displayed, this Issue will close.
